variable "INSTANCE_TYPE"    {}
variable "TAGS"             {}
variable "GIT_USR"          {}
variable "GIT_PSW"          {}
variable "SSH_USR"          {}
variable "SSH_PSW"          {}
variable "PORTS"            {}
variable "R_USR" {}
variable "R_PSW" {}
variable "API_KEY" {}
variable "LICENSE_KEY" {}
